### ISSUE TITLE
Not working on Oculus Quest

### ISSUE THREAD

**Issue by MarkivK89** [supermedium/aframe-super-shooter#2]
Tested: https://supermedium.github.io/aframe-super-shooter-kit/examples/supercraft/ on Quest.

Test result:
- Shooting using my index finger gives audio, though no visual effect
- I cannot start the game
- Game looks (sounds) awesome on desktop.

**Comment by ngokevin** [comment]
I merged https://github.com/supermedium/aframe-super-shooter-kit/pull/1 which might help!

**Comment by kwadroke** [comment]
I just tried it on my Quest. It's working, but, the guns are pointing up/parallel with the handles on the Quest Controllers. Not pointing forward like a normal gun. More like a lightsaber.

**Comment by ngokevin** [comment]
I see. For Touch controllers, need to rotate the meshes to match. Usually, we have a controller.js file that detects the controller type and makes any necessary adjustments (mesh rotations, raycaster directions). Won't get around to updating until maybe next week, but you can rotate the controller or shoot direction for now?

**Comment by kwadroke** [comment]
I can rotate the controller and shoot the creatures. Just feels off at the moment.

**Comment by Firepal** [comment]
The A-Frame version used in the example is outdated.
The latest version of A-Frame has a much more stable oculus-touch-controller that recognizes and fixes the orientation of the Oculus Touch Gen 2 controllers.

[Here's an edit of the supercraft example with the latest A-Frame](https://firepal.tilde.team/3D/supercraft/)

**Comment by Firepal** [comment]
The example uses TWEEN.js, which is no longer included in new A-Frame releases and was replaced with the animation component, so this would require more work than just adding a new version of A-Frame...

**Comment by Firepal** [comment]
Decided to use the old A-Frame version and keep the Tween code.
Manually setting the orientation offset of the controller works, probably breaks CV1 controller orientation though.
